# ------------------------ #
# Configuration des Builds #
# ------------------------ #

variables:
    GIT_SUBMODULE_STRATEGY: recursive

# -------------------- #
# Compilation du Sujet #
# -------------------- #

portfolio:
    script:
        - ./make-portfolio.sh
    artifacts:
        paths:
            - portfolio.pdf
    tags:
        - marathon-sujet
