# ------------------------ #
# Configuration des Builds #
# ------------------------ #

variables:
    GIT_SUBMODULE_STRATEGY: recursive

# ------------------------ #
# Compilation du Portfolio #
# ------------------------ #

portfolio:
    script:
        - ./make-portfolio.sh
    artifacts:
        paths:
            - portfolio.pdf
    tags:
        - pandoc

# ------------------------ #
# Compilation des tableaux #
# ------------------------ #

tables:
    script:
        - ./make-tables.sh
    artifacts:
        paths:
            - S*.pdf
    tags:
        - pandoc
