# ------------------------ #
# Configuration des Builds #
# ------------------------ #

variables:
    GIT_SUBMODULE_STRATEGY: recursive

# ------------------------ #
# Compilation du Portfolio #
# ------------------------ #

portfolio:
    script:
        - ./make-portfolio.sh
    artifacts:
        paths:
            - portfolio.pdf
    tags:
        - pandoc

slides:
    script:
        - ./make-slides.sh
    artifacts:
        paths:
            - portfolio-slides.pdf
    tags:
        - pandoc
